/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMaintenanceDialog: typeof import('./src/components/AddMaintenanceDialog.vue')['default']
    AddRoomDialog: typeof import('./src/components/AddRoomDialog.vue')['default']
    AddWishDialog: typeof import('./src/components/AddWishDialog.vue')['default']
    BudgetCategoryDetail: typeof import('./src/components/BudgetCategoryDetail.vue')['default']
    BudgetSetup: typeof import('./src/components/BudgetSetup.vue')['default']
    CompleteTaskDialog: typeof import('./src/components/CompleteTaskDialog.vue')['default']
    CreatePolicyDialog: typeof import('./src/components/CreatePolicyDialog.vue')['default']
    CreateReturnDialog: typeof import('./src/components/CreateReturnDialog.vue')['default']
    DeleteRoomDialog: typeof import('./src/components/DeleteRoomDialog.vue')['default']
    FrameSharePanel: typeof import('./src/components/FrameSharePanel.vue')['default']
    HealthScoreWidget: typeof import('./src/components/HealthScoreWidget.vue')['default']
    HomeNavbar: typeof import('./src/components/HomeNavbar.vue')['default']
    HomeSettingsPanel: typeof import('./src/components/HomeSettingsPanel.vue')['default']
    HomeSidebar: typeof import('./src/components/HomeSidebar.vue')['default']
    HouseholdMemberAvatar: typeof import('./src/components/HouseholdMemberAvatar.vue')['default']
    ICalSubscribePanel: typeof import('./src/components/ICalSubscribePanel.vue')['default']
    InsuranceCard: typeof import('./src/components/InsuranceCard.vue')['default']
    MarkReceivedDialog: typeof import('./src/components/MarkReceivedDialog.vue')['default']
    PhotoSection: typeof import('./src/components/PhotoSection.vue')['default']
    PlaceholderWidget: typeof import('./src/components/PlaceholderWidget.vue')['default']
    RecallBanner: typeof import('./src/components/RecallBanner.vue')['default']
    ReturnCard: typeof import('./src/components/ReturnCard.vue')['default']
    RoomCardGrid: typeof import('./src/components/RoomCardGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanConfirmationDialog: typeof import('./src/components/ScanConfirmationDialog.vue')['default']
    SetTargetDialog: typeof import('./src/components/SetTargetDialog.vue')['default']
    WarrantyCard: typeof import('./src/components/WarrantyCard.vue')['default']
  }
}
